"""
Version-robust model persistence.

Why not plain ``joblib.dump``? Because a pickled estimator is coupled to the
exact library build that wrote it. The original bundle did exactly that, and the
server printed this on every boot::

    WARNING: If you are loading a serialized model ... generated by an older
    version of XGBoost, please export the model by calling `Booster.save_model`
    from that version first ...

A silent dependency bump could therefore have changed — or broken — the live
model. This module uses each library's **own** stable format instead:

===============  ==================  ==========================================
Estimator        Format              Why
===============  ==================  ==========================================
XGBoost          ``.json`` (ubj)     forward/backward compatible by design
LightGBM         ``.txt``            textual, version-tolerant model dump
CatBoost         ``.cbm``            CatBoost's portable binary format
scikit-learn     ``.joblib``         no native format exists; pinned versions
===============  ==================  ==========================================

The dashboard's fused ensemble (a ``VotingRegressor``) is stored as its
*components* plus a ``FusedEnsemble`` wrapper that reproduces the ensemble's
uniform-weight mean. That wrapper is mathematically equivalent to the sklearn
object it replaces (asserted in ``tests/test_model_io.py``) and survives the
library upgrades that pickling does not.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

import joblib
import numpy as np


# ---------------------------------------------------------------------------
# Saving
# ---------------------------------------------------------------------------
def _kind_of(obj) -> str:
    name = type(obj).__module__.split(".")[0]
    cls = type(obj).__name__
    if name == "xgboost":
        return "xgboost"
    if name == "lightgbm":
        return "lightgbm"
    if name == "catboost":
        return "catboost"
    if cls in {"Booster"} and name in {"xgboost", "lightgbm"}:
        return name
    return "sklearn"


def _target_path(stem: Path, extension: str) -> Path:
    """Append an extension to the stem **without** discarding dotted names.

    ``Path.with_suffix`` replaces the last suffix, so ``q0.025`` + ``.txt``
    collapsed to ``q0.txt`` — silently overwriting eight of the nine quantile
    models with the ninth, which then served every quantile level from a single
    estimator. Appending the extension keeps dotted identifiers intact.
    """
    return stem.parent / f"{stem.name}{extension}"


def save_model(obj, stem: str | Path) -> Path:
    """Persist ``obj`` in the most portable format available.

    ``stem`` is a path without extension; the real suffix is appended and the
    written path is returned.
    """
    stem = Path(stem)
    stem.parent.mkdir(parents=True, exist_ok=True)
    kind = _kind_of(obj)

    try:
        if kind == "xgboost" and hasattr(obj, "save_model"):
            path = _target_path(stem, ".json")
            obj.save_model(path)              # XGBRegressor delegates to the Booster
            return path
        if kind == "lightgbm":
            boosters = getattr(obj, "booster_", None)
            path = _target_path(stem, ".txt")
            if boosters is not None:
                boosters.save_model(str(path))
            else:                             # already a raw Booster
                obj.save_model(str(path))
            return path
        if kind == "catboost" and hasattr(obj, "save_model"):
            path = _target_path(stem, ".cbm")
            obj.save_model(str(path))
            return path
    except Exception:  # noqa: BLE001 - fall back rather than lose the model
        pass

    path = _target_path(stem, ".joblib")
    joblib.dump(obj, path, compress=3)
    return path


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------
def load_model(path: str | Path):
    """Load whatever :func:`save_model` wrote, dispatching on the suffix."""
    path = Path(path)
    suffix = path.suffix.lower()

    if suffix == ".json":
        import xgboost as xgb
        booster = xgb.Booster()
        booster.load_model(path)
        return booster
    if suffix == ".txt":
        import lightgbm as lgb
        return lgb.Booster(model_file=str(path))
    if suffix == ".cbm":
        from catboost import CatBoostRegressor
        model = CatBoostRegressor()
        model.load_model(str(path))
        return model
    return joblib.load(path)


def load_if_available(path: str | Path):
    """Load a model, returning ``None`` if an optional dependency is missing."""
    try:
        return load_model(path)
    except Exception:  # noqa: BLE001 - a missing library drops one menu entry
        return None


# ---------------------------------------------------------------------------
# Fused ensemble (component-wise persistence)
# ---------------------------------------------------------------------------
class FusedEnsemble:
    """Uniform-weight mean of several regressors.

    Equivalent to ``sklearn.ensemble.VotingRegressor`` with ``weights=None`` for
    regression (which averages the base predictions), but assembled from models
    stored in portable formats so it can be rebuilt after a dependency upgrade.
    """

    def __init__(self, components: Sequence[tuple[str, object]]):
        if not components:
            raise ValueError("FusedEnsemble needs at least one component")
        self.components = list(components)

    @property
    def component_names(self) -> list[str]:
        return [name for name, _ in self.components]

    def predict(self, X) -> np.ndarray:
        preds = np.asarray([self._component_predict(m, X) for _, m in self.components],
                           dtype=float)
        return preds.mean(axis=0)

    @staticmethod
    def _component_predict(model, X) -> np.ndarray:
        """Call a component in the dialect it expects.

        A native XGBoost ``Booster`` requires a ``DMatrix`` rather than a
        DataFrame, and a LightGBM ``Booster`` is happiest with a plain array (it
        would otherwise warn about feature-name mapping). Handling that here keeps
        the portable formats invisible to the rest of the app.
        """
        module = type(model).__module__.split(".")[0]
        class_name = type(model).__name__
        if module == "xgboost" and class_name == "Booster":
            # Raw native booster; the sklearn wrapper handles DataFrames itself.
            import xgboost as xgb
            if not isinstance(X, xgb.DMatrix):
                X = xgb.DMatrix(X)
        elif module == "lightgbm" and class_name == "Booster" and hasattr(X, "to_numpy"):
            X = X.to_numpy()            # avoids a feature-name mapping warning
        return np.asarray(model.predict(X), dtype=float)

    # sklearn-compatible surface used elsewhere in the app
    def get_params(self, deep: bool = True) -> dict:  # pragma: no cover - parity only
        return {"components": self.component_names}

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"FusedEnsemble({', '.join(self.component_names)})"


def save_ensemble(components: Iterable[tuple[str, object]], directory: str | Path) -> dict:
    """Write every component to ``directory``; return the manifest to store."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    files: list[dict] = []
    for name, model in components:
        written = save_model(model, directory / name)
        files.append({"name": name, "file": written.name, "kind": _kind_of(model)})
    return {"kind": "fused_mean", "components": files}


def load_ensemble(manifest: dict, directory: str | Path) -> FusedEnsemble | None:
    """Rebuild a :class:`FusedEnsemble` from a manifest, or ``None`` if incomplete."""
    directory = Path(directory)
    loaded: list[tuple[str, object]] = []
    for entry in (manifest or {}).get("components", []):
        model = load_if_available(directory / entry["file"])
        if model is None:
            return None                       # an optional dependency is missing
        loaded.append((entry["name"], model))
    return FusedEnsemble(loaded) if loaded else None
